Application/CSM/CSM.Web/Models/ActivityViewModel.cs
using System;
using System.Collections.Generic;
using CSM.Entity;

namespace CSM.Web.Models
{
    [Serializable]
    public class ActivityViewModel
    {
        public CustomerInfoViewModel CustomerInfo { get; set; }
        public ActivitySearchFilter SearchFilter { get; set; }
        public IEnumerable<ServiceRequestActivityResult> ActivityList { get; set; }
    }
}

Application/CSM/CSM.Web/Controllers/ActivityController.cs
using System;
using System.Web.Mvc;
using CSM.Business;
using CSM.Common.Utilities;
using CSM.Entity;
using CSM.Web.Controllers.Common;
using CSM.Web.Filters;
using CSM.Web.Models;
using log4net;

namespace CSM.Web.Controllers
{
    [CheckUserSession]
    public class ActivityController : BaseController
    {
        private AuditLogEntity _auditLog;
        private ICommonFacade _commonFacade;
        private IActivityFacade _activityFacade;
        private LogMessageBuilder _logMsg = new LogMessageBuilder();
        private static readonly ILog Logger = LogManager.GetLogger(typeof(ActivityController));

        [CheckUserRole(ScreenCode.ViewCustomerActivity)]
        public ActionResult List(string encryptedString)
        {
            int? customerId = encryptedString.ToCustomerId();
            Logger.Info(_logMsg.Clear().SetPrefixMsg("InitSearch ActivityLog").Add("CustomerId", customerId).ToInputLogString());

            try
            {
                if (customerId == null)
                {
                    return RedirectToAction("Search", "Customer");
                }

                CustomerInfoViewModel custInfoVM = this.MappingCustomerInfoView(customerId.Value);
                ActivityViewModel activityVM = new ActivityViewModel();
                activityVM.CustomerInfo = custInfoVM;

                _commonFacade = new CommonFacade();
                _activityFacade = new ActivityFacade();

                var today = DateTime.Today;
                var month = new DateTime(today.Year, today.Month, 1);
                var numMonthsActivity = _commonFacade.GetNumMonthsActivity();
                var activityStartDateValue = month.AddMonths(-1 * numMonthsActivity); //"2015-01-01".ParseDateTime("yyyy-MM-dd");
                var subsType = custInfoVM.SubscriptType;

                activityVM.SearchFilter = new ActivitySearchFilter
                {
                    ActivityStartDateTime = activityStartDateValue.FormatDateTime(Constants.DateTimeFormat.DefaultFullDateTime),
                    ActivityEndDateTime = DateTime.Now.FormatDateTime(Constants.DateTimeFormat.DefaultFullDateTime),
                    CardNo = custInfoVM.CardNo,
                    SubsTypeCode = subsType != null ? subsType.SubscriptTypeCode : null,
                    PageNo = 1,
                    PageSize = _commonFacade.GetPageSizeStart(),
                    SortField = "ActivityID",
                    SortOrder = "DESC"
                };

                ViewBag.PageSize = activityVM.SearchFilter.PageSize;
                ViewBag.PageSizeList = _commonFacade.GetPageSizeList();
                ViewBag.Message = string.Empty;

                return View(activityVM);
            }
            catch (Exception ex)
            {
                Logger.Error("Exception occur:\n", ex);
                Logger.Info(_logMsg.Clear().SetPrefixMsg("InitSearch ActivityLog").Add("Error Message", ex.Message).ToFailLogString());
                return Error(new HandleErrorInfo(ex, this.ControllerContext.RouteData.Values["controller"].ToString(),
                    this.ControllerContext.RouteData.Values["action"].ToString()));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CheckUserRole(ScreenCode.ViewCustomerActivity)]
        public ActionResult ActivityList(ActivitySearchFilter searchFilter)
        {
            Logger.Info(_logMsg.Clear().SetPrefixMsg("Search Activity").ToInputLogString());

            try
            {
                if (ModelState.IsValid)
                {
                    _auditLog = new AuditLogEntity();
                    _auditLog.Module = Constants.Module.Customer;
                    _auditLog.Action = Constants.AuditAction.ActivityLog;
                    _auditLog.IpAddress = ApplicationHelpers.GetClientIP();
                    _auditLog.CreateUserId = this.UserInfo.UserId;

                    _commonFacade = new CommonFacade();
                    _activityFacade = new ActivityFacade();
                    ActivityViewModel activityVM = new ActivityViewModel();

                    //if (string.IsNullOrWhiteSpace(searchFilter.JsonActivities))
                    //{
                    //    var results = _activityFacade.GetActivityLogList(_auditLog, searchFilter);
                    //    searchFilter.JsonActivities = JsonConvert.SerializeObject(results);
                    //}

                    activityVM.SearchFilter = searchFilter;
                    activityVM.ActivityList = _activityFacade.GetServiceRequestActivityResults(_auditLog, searchFilter);
                    if (activityVM.ActivityList != null)
                    {
                        activityVM.SearchFilter.IsConnect = 1;

                        ViewBag.PageSize = activityVM.SearchFilter.PageSize;
                        ViewBag.PageSizeList = _commonFacade.GetPageSizeList();

                        Logger.Info(_logMsg.Clear().SetPrefixMsg("Search Activity").ToSuccessLogString());
                        return PartialView("~/Views/Activity/_ActivityList.cshtml", activityVM);
                    }
                    else
                    {
                        return SRActivityList(searchFilter);
                    }
                    
                }

                return Json(new
                {
                    Valid = false,
                    Error = string.Empty,
                    Errors = GetModelValidationErrors()
                });
            }
            catch (CustomException cex)
            {
                Logger.Info(_logMsg.Clear().SetPrefixMsg("Search Activity").Add("Error Message", cex.Message).ToFailLogString());
                return Json(new
                {
                    Valid = false,
                    Error = cex.Message
                });
            }
            catch (Exception ex)
            {
                Logger.Error("Exception occur:\n", ex);
                Logger.Info(_logMsg.Clear().SetPrefixMsg("Search Activity").Add("Error Message", ex.Message).ToFailLogString());
                return Error(new HandleErrorInfo(ex, this.ControllerContext.RouteData.Values["controller"].ToString(),
                    this.ControllerContext.RouteData.Values["action"].ToString()));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CheckUserRole(ScreenCode.ViewCustomerActivity)]
        public ActionResult SRActivityList(ActivitySearchFilter searchFilter)
        {
            Logger.Info(_logMsg.Clear().SetPrefixMsg("Search SR Activity").ToInputLogString());

            try
            {
                searchFilter.SrOnly = false;

                if (ModelState.IsValid)
                {
                    _commonFacade = new CommonFacade();
                    _activityFacade = new ActivityFacade();
                    ActivityViewModel activityVM = new ActivityViewModel();

                    activityVM.SearchFilter = searchFilter;
                    activityVM.ActivityList = _activityFacade.GetSRActivityList(searchFilter);

                    activityVM.SearchFilter.IsConnect = 0;

                    ViewBag.PageSize = activityVM.SearchFilter.PageSize;
                    ViewBag.PageSizeList = _commonFacade.GetPageSizeList();

                    Logger.Info(_logMsg.Clear().SetPrefixMsg("Search Activity").ToSuccessLogString());
                    return PartialView("~/Views/Activity/_ActivityList.cshtml", activityVM);
                }

                return Json(new
                {
                    Valid = false,
                    Error = string.Empty,
                    Errors = GetModelValidationErrors()
                });
            }
            catch (Exception ex)
            {
                Logger.Error("Exception occur:\n", ex);
                Logger.Info(_logMsg.Clear().SetPrefixMsg("Search Activity").Add("Error Message", ex.Message).ToFailLogString());
                return Error(new HandleErrorInfo(ex, this.ControllerContext.RouteData.Values["controller"].ToString(),
                    this.ControllerContext.RouteData.Values["action"].ToString()));
            }
        }
    }
}

Application/CSM/CSM.Web/Views/Activity/List.cshtml
@using CSM.Common.Resources
@using CSM.Entity
@model CSM.Web.Models.ActivityViewModel
@{
    ViewBag.Title = Resource.Lbl_CustomerInformation;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MainMenu
{
    @Html.Action("MainMenu", "MenuNavigator", new { selectedMenu = MenuCode.Customer })
}

@section Breadcrumb {
    <strong class="font-blue">@Resource.Lbl_Customer &rsaquo;&rsaquo;</strong>
    <strong class="font-blue">
        @Html.ActionLink(Resource.Lbl_SearchCustomer, "Search", "Customer", new { @skip = "1" }, new { @class = "font-blue" })
    </strong>
    <strong class="font-green-jungle">&rsaquo;&rsaquo; @Resource.Lbl_CustomerInformation </strong>
}

@if (Model != null)
{
    <div id="dvForm" class="form-box">
        <h5 class="form-title">@Resource.Lbl_CustomerInformation</h5>
        @Html.HiddenFor(model => model.CustomerInfo.CustomerId, new { @id = "hddCustomerId" })
        @if (Model.CustomerInfo != null)
        {
            Html.RenderPartial("~/Views/Customer/_CustomerInfo.cshtml", Model.CustomerInfo);
        }
        <div class="clearfix"></div>

        @Html.Action("CustomerTab", "MenuNavigator", new { selectedTab = CustomerTabCode.Activity, customerId = @Model.CustomerInfo.CustomerId })
        @*<div class="clearfix"></div>
            <div class="pull-left padding-top-5">
                <button id="btnNewActivity" type="button" class="btn btn-green btn-sm">
                    <i class="fa fa-plus"></i>&nbsp;New Activity
                </button>
            </div>*@
        <div class="clearfix"></div>
        <div class="tab-content">
            <div id="tabActivity" class="tab-pane fade in active">
                <div class="pull-right" id="dvServiceMsg"></div>
                <div class="clear"></div>
                <div id="dvSearchResult">
                    @{ Html.RenderPartial("~/Views/Activity/_ActivityList.cshtml", Model); }
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <input type="hidden" id="hiddenSubscriptionTypeId" value="@(Model.CustomerInfo != null && Model.CustomerInfo.SubscriptType != null && Model.CustomerInfo.SubscriptType.SubscriptTypeId.HasValue ? (Model.CustomerInfo.SubscriptType.SubscriptTypeId.Value + "") : "")" />
    <input type="hidden" id="hiddenSubscriptionId" value="@(Model.CustomerInfo != null ? Model.CustomerInfo.CardNo : "")" />
}
<div id="dvTarget"></div>
@section masterjs
{
    <script type="text/javascript">
        var searchFilter;
        var successFilter;

        $jq(document).ready(function () {
            initializeSearchFilter();
            initializePaging();
            loadData();
        });

        function initializeSearchFilter() {
            searchFilter = {
                JsonActivities: '',
                ActivityStartDateTime: '@Model.SearchFilter.ActivityStartDateTime',
                ActivityEndDateTime: '@Model.SearchFilter.ActivityEndDateTime',
                CardNo: '@Model.SearchFilter.CardNo',
                SubsTypeCode: '@Model.SearchFilter.SubsTypeCode',
                IsConnect: $jq('#hddIsConnect').val(),
                CustomerId: $jq('#hddCustomerId').val(),
                SrOnly: 'false',
                PageNo: '@Model.SearchFilter.PageNo',
                PageSize: '@Model.SearchFilter.PageSize',
                SortField: '@Model.SearchFilter.SortField',
                SortOrder: '@Model.SearchFilter.SortOrder'
            };
            successFilter = searchFilter;
        };

        function initializePaging() {
            $jq("#dvSearchResult .input-page").change(function (event) {
                searchFilter = successFilter;
                searchFilter.PageNo = $jq(this).val();
                loadData();
                return false;
            }).keypress(function (event) {
                return validateDigit(event);
            });

            $jq("#dvSearchResult #pagesizelist").change(function (event) {
                searchFilter = successFilter;
                searchFilter.PageNo = "1";
                searchFilter.PageSize = $jq(this).val();
                loadData();
                return false;
            });

            $jq('#dvSearchResult .pagination ul li a').on('click', function (event) {
                searchFilter = successFilter;
                searchFilter.PageNo = getUrlParameter($jq(this).attr("href"), "page");
                loadData();
                return false;
            });

            //$jq("#tblActivityList").tableHeadFixer({ "head": false, "left": 3 });
        };

        function loadData() {
            var isConnect = $jq('#hddIsConnect').val();
            var subscriptionTypeId = $jq("#hiddenSubscriptionTypeId").val();
            var subscriptionId = $jq("#hiddenSubscriptionId").val();
            var searchUrl = '@Url.Action("ActivityList", "Activity")';

            if (isConnect == '0' || subscriptionTypeId == "" || subscriptionId == "") {
                searchUrl = '@Url.Action("SRActivityList", "Activity")';
            }

            searchFilter.JsonActivities = $jq('#hddJsonActivities').val();
            searchFilter.IsConnect = isConnect;

            $jq.ajax({
                url: searchUrl,
                type: "POST",
                data: addAntiForgeryToken(searchFilter),
                beforeSend: function () { $jq("#dvLoading").show(); },
                complete: function () { $jq("#dvLoading").hide(); },
                success: function (result) {
                    if (result.Valid == null) {
                        $jq('#dvServiceMsg').html('');
                        $jq("#dvSearchResult").html('');
                        successFilter = searchFilter;
                        $jq("#dvSearchResult").html(result);

                        isConnect = $jq('#hddIsConnect').val();

                        if (isConnect == '0' || subscriptionTypeId == "" || subscriptionId == "") {
                            var errorMsg = '@Resource.Msg_CannotConnectCARService';
                            var message = "<span class='badge badge-warning'>" + errorMsg + '</span>';
                            $jq('#dvServiceMsg').html(message);
                        }
                        initializePaging();
                    } else {
                        showServiceErrors(result);

                        if (isConnect == '1') {
                            $jq('#hddIsConnect').val('0');
                            loadData();
                        }
                    }
                },
                error: function (xhr) {
                    var handleMsg = '@CSM.Common.Resources.Resource.Error_System';
                    ajaxErrorHandling(xhr, handleMsg, '@FormsAuthentication.LoginUrl', '@Url.Action("AccessDenied", "User")');
                }
            });

            return false;
        }

        function sortField(selectedSortField) {
            if (selectedSortField == searchFilter.SortField)
                searchFilter.SortOrder = (searchFilter.SortOrder == 'ASC') ? 'DESC' : 'ASC';
            else
                searchFilter.SortOrder = 'ASC';
            searchFilter.SortField = selectedSortField;
            searchFilter.PageNo = 1;
            loadData();
        }
    </script>
}