Application/CSM/CSM.Web/Models/JobViewModel.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using CSM.Common.Utilities;
using CSM.Entity;
using System.ComponentModel.DataAnnotations;

namespace CSM.Web.Models
{
    [Serializable]
    public class JobViewModel
    {
        public int? JobId { get; set; }
        public string Sender { get; set; }
        public string Subject { get; set; }

        [AllowHtml]
        public string Content { get; set; }

        public int SequenceNo { get; set; }
        public string StatusDisplay { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public string Channel { get; set; }
        public string ProductGroup { get; set; }  
        public string Product { get; set; }
        public string Type { get; set; }
        public string SubArea { get; set; }   

        //SR
        public string SrNo { get; set; }
        public int SR_Status { get; set; }
        public string SrChannel { get; set; }
        public string SrSubject { get; set; }

        [AllowHtml]
        public string SrRemark { get; set; }
        public string SrOwner { get; set; }
        public string SrDelegator { get; set; }
        public string SrCreateDate { get; set; }
        public string SrCreateUser { get; set; } 
        public string SrUpdateUser { get; set; }
        public string SrUpdateDate { get; set; }
        public string SrMediaSource { get; set; } 

        //Customer
        public string FirstNameThai { get; set; }
        public string LastNameThai { get; set; }
        public string FirstNameEnglish { get; set; }
        public string LastNameEnglish { get; set; }
        public string ActionBy { get; set; }

        //Attachment
        public List<AttachmentEntity> Attachments { get; set; }
        public IEnumerable<CommunicationPoolEntity> CommunicationPoolList { get; set; }
        public CommPoolSearchFilter SearchFilter { get; set; }

        public string IsSelected { get; set; }
        
        [Display(Name = "Lbl_Remark", ResourceType = typeof(CSM.Common.Resources.Resource))]
        [LocalizedRequired(ErrorMessage = "ValErr_RequiredField")]
        public string Remark { get; set; }
        public int? JobStatus { get; set; }
    }
}

Application/CSM/CSM.Web/Controllers/JobController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using CSM.Business;
using CSM.Common.Utilities;
using CSM.Entity;
using CSM.Web.Controllers.Common;
using CSM.Web.Filters;
using CSM.Web.Models;
using log4net;
using CSM.Common.Resources;
using System.Globalization;

namespace CSM.Web.Controllers
{
    [CheckUserSession]
    public class JobController : BaseController
    {
        private ICommonFacade _commonFacade;
        private ICommPoolFacade _commPoolFacade;
        private LogMessageBuilder _logMsg = new LogMessageBuilder();
        private static readonly ILog Logger = LogManager.GetLogger(typeof(JobController));

        [CheckUserRole(ScreenCode.SearchCommPool)]
        public ActionResult Search()
        {
            Logger.Info(_logMsg.Clear().SetPrefixMsg("InitSearch Job").ToInputLogString());
            try
            {
                _commonFacade = new CommonFacade();
                _commPoolFacade = new CommPoolFacade();

                ViewBag.jobstatus = _commPoolFacade.GetJobStatusSelectList(Resource.Ddl_Status_All, Constants.ApplicationStatus.All);
                ViewBag.channel = _commPoolFacade.GetChannelWithEmailSelectList(Resource.Ddl_Status_All, Constants.ApplicationStatus.All);
                ViewBag.srstatus = _commPoolFacade.GetSRStatusSelectList(Resource.Ddl_Status_All, Constants.ApplicationStatus.All);

                JobViewModel jobVM = new JobViewModel();
                jobVM.SearchFilter = new CommPoolSearchFilter
                {
                    FirstName = string.Empty,
                    LastName = string.Empty,
                    JobStatus = null,
                    Channel = null,
                    Subject = string.Empty,
                    From = string.Empty,
                    DateFrom = string.Empty,
                    DateTo = string.Empty,
                    ActionBy = string.Empty,
                    SRId = string.Empty,
                    SRStatus = null,
                    JobDateFrom = string.Empty,
                    JobDateTo = string.Empty,
                    CreatorSR = string.Empty,
                    OwnerSR = string.Empty,
                    User = null,
                    PageNo = 1,
                    PageSize = _commonFacade.GetPageSizeStart(),
                    SortField = "JobId",
                    SortOrder = "DESC"
                };

                var defSearch = _commonFacade.GetShowhidePanelByUserId(this.UserInfo, Constants.Page.CommunicationPage);

                if (defSearch != null)
                {
                    jobVM.IsSelected = defSearch.IsSelectd ? "1" : "0";
                }
                else
                {
                    jobVM.IsSelected = "0";
                }

                ViewBag.PageSize = jobVM.SearchFilter.PageSize;
                ViewBag.PageSizeList = _commonFacade.GetPageSizeList();
                ViewBag.Message = string.Empty;

                return View(jobVM);
            }
            catch (Exception ex)
            {
                Logger.Error("Exception occur:\n", ex);
                Logger.Info(_logMsg.Clear().SetPrefixMsg("InitSearch Job").Add("Error Message", ex.Message).ToFailLogString());
                return Error(new HandleErrorInfo(ex, this.ControllerContext.RouteData.Values["controller"].ToString(),
                    this.ControllerContext.RouteData.Values["action"].ToString()));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CheckUserRole(ScreenCode.SearchCommPool)]
        public ActionResult JobList(CommPoolSearchFilter searchFilter)
        {
            Logger.Info(_logMsg.Clear().SetPrefixMsg("InitSearch Job")
                .Add("FirstName", searchFilter.FirstName).Add("LastName", searchFilter.LastName));

            try
            {
                _commonFacade = new CommonFacade();
                int? monthOfReportExport = _commonFacade.GetCacheParamByName(Constants.ParameterName.ReportExportDate).ParamValue.ToNullable<int>();

                #region "Validation"

                if (!string.IsNullOrWhiteSpace(searchFilter.FirstName)
                    && searchFilter.FirstName.ExtractString().Length < Constants.MinLenght.SearchTerm)
                {
                    ModelState["FirstName"].Errors.Clear();
                    ModelState["FirstName"].Errors.Add(string.Format(CultureInfo.InvariantCulture, Resource.ValErr_MinLength, Constants.MinLenght.SearchTerm));
                }

                if (!string.IsNullOrWhiteSpace(searchFilter.LastName) &&
                    searchFilter.LastName.ExtractString().Length < Constants.MinLenght.SearchTerm)
                {
                    ModelState["LastName"].Errors.Clear();
                    ModelState["LastName"].Errors.Add(string.Format(CultureInfo.InvariantCulture, Resource.ValErr_MinLength, Constants.MinLenght.SearchTerm));
                }

                bool isValid = TryUpdateModel(searchFilter);

                if (!string.IsNullOrEmpty(searchFilter.DateFrom) && !searchFilter.DateFromValue.HasValue)
                {
                    isValid = false;
                    ModelState.AddModelError("txtFromDate", Resource.ValErr_InvalidDate);
                }
                else if(searchFilter.DateFromValue.HasValue)
                {
                    if (searchFilter.DateFromValue.Value > DateTime.Now.Date)
                    {
                        isValid = false;
                        ModelState.AddModelError("txtFromDate", Resource.ValErr_InvalidDate_MustLessThanToday);
                    }
                }

                if (!string.IsNullOrEmpty(searchFilter.DateTo) && !searchFilter.DateToValue.HasValue)
                {
                    isValid = false;
                    ModelState.AddModelError("txtToDate", Resource.ValErr_InvalidDate);
                }
                else if (searchFilter.DateToValue.HasValue)
                {
                    if (searchFilter.DateToValue.Value > DateTime.Now.Date)
                    {
                        isValid = false;
                        ModelState.AddModelError("txtToDate", Resource.ValErr_InvalidDate_MustLessThanToday);
                    }
                }

                if (searchFilter.DateFromValue.HasValue && searchFilter.DateToValue.HasValue
                    && searchFilter.DateFromValue.Value > searchFilter.DateToValue.Value)
                {
                    isValid = false;
                    ModelState.AddModelError("dvDateRange", Resource.ValErr_InvalidDateRange);
                }

                // ActionDate
                if (!string.IsNullOrEmpty(searchFilter.DateFrom) && string.IsNullOrEmpty(searchFilter.DateTo))
                {
                    isValid = false;
                    ModelState.AddModelError("txtToDate", Resource.ValErr_Required);
                }
                if (string.IsNullOrEmpty(searchFilter.DateFrom) && !string.IsNullOrEmpty(searchFilter.DateTo))
                {
                    isValid = false;
                    ModelState.AddModelError("txtFromDate", Resource.ValErr_Required);
                }

                if (!string.IsNullOrEmpty(searchFilter.DateFrom) && !string.IsNullOrEmpty(searchFilter.DateTo))
                {
                    if (searchFilter.DateToValue.Value > searchFilter.DateFromValue.Value.AddMonths(monthOfReportExport.Value))
                    {
                        isValid = false;
                        ModelState.AddModelError("dvDateRange", string.Format(CultureInfo.InvariantCulture, Resource.ValError_ReportExportDuration, monthOfReportExport.Value));
                    }
                }

                //JobDate
                if (!string.IsNullOrEmpty(searchFilter.JobDateFrom) && !searchFilter.JobDateFromValue.HasValue)
                {
                    isValid = false;
                    ModelState.AddModelError("txtJobFromDate", Resource.ValErr_InvalidDate);
                }
                else if (searchFilter.JobDateFromValue.HasValue)
                {
                    if (searchFilter.JobDateFromValue.Value > DateTime.Now.Date)
                    {
                        isValid = false;
                        ModelState.AddModelError("txtJobFromDate", Resource.ValErr_InvalidDate_MustLessThanToday);
                    }
                }

                if (!string.IsNullOrEmpty(searchFilter.JobDateTo) && !searchFilter.JobDateToValue.HasValue)
                {
                    isValid = false;
                    ModelState.AddModelError("txtJobToDate", Resource.ValErr_InvalidDate);
                }
                else if (searchFilter.JobDateToValue.HasValue)
                {
                    if (searchFilter.JobDateToValue.Value > DateTime.Now.Date)
                    {
                        isValid = false;
                        ModelState.AddModelError("txtJobToDate", Resource.ValErr_InvalidDate_MustLessThanToday);
                    }
                }

                if (searchFilter.JobDateFromValue.HasValue && searchFilter.JobDateToValue.HasValue
                    && searchFilter.JobDateFromValue.Value > searchFilter.JobDateToValue.Value)
                {
                    isValid = false;
                    ModelState.AddModelError("dvJobDateRange", Resource.ValErr_InvalidDateRange);
                }

                //--------------------------
                if (!string.IsNullOrEmpty(searchFilter.JobDateFrom) && string.IsNullOrEmpty(searchFilter.JobDateTo))
                {
                    isValid = false;
                    ModelState.AddModelError("txtJobToDate", Resource.ValErr_Required);
                }
                if (string.IsNullOrEmpty(searchFilter.JobDateFrom) && !string.IsNullOrEmpty(searchFilter.JobDateTo))
                {
                    isValid = false;

Application/CSM/CSM.Web/Views/Job/_JobList.cshtml
@model CSM.Web.Models.JobViewModel
@using CSM.Common.Resources
@using CSM.Common.Utilities
@using MvcPaging;
@helper LabelForSort(string headerText, string fieldName, string sortField, string sortOrder)
{
    <a href="javascript:;" onclick="sortField('@fieldName');return false;">
        @headerText
        @if (fieldName.ToLower().Equals(sortField.ToLower()))
        {
            if (sortOrder.Equals("ASC"))
            {<i class="fa fa-sort-asc"></i>}
            else
            {<i class="fa fa-sort-desc"></i> }
        }
        else
        {<i class="fa fa-sort"></i>}
    </a>
}
@if (Model.CommunicationPoolList == null || Model.SearchFilter.TotalRecords == 0)
{
    string sortField = Model.SearchFilter.SortField;
    string sortOrder = Model.SearchFilter.SortOrder;
    <div class="table-responsive margin-top-10">
        <table class="table table-hover datatable">
            <thead>
                <tr>
                    <th class="center text-nowrap" style="width:10%!important;">Action</th>
                    <th class="center text-nowrap" style="width:10%!important;">Attach File</th>
                    <th class="center text-nowrap" style="width:10%!important;">Channel</th>
                    <th class="center text-nowrap" style="width:10%!important;">From</th>
                    <th class="center text-nowrap" style="width:10%!important;">Job Status</th>
                    <th class="center text-nowrap" style="width:10%!important;">Job Date</th>
                    <th class="center text-nowrap" style="width:10%!important;">Subject</th>
                    <th class="center text-nowrap" style="width:10%!important;">ชื่อลูกค้า</th>
                    <th class="center text-nowrap" style="width:10%!important;">นามสกุลลูกค้า</th>
                    <th class="center text-nowrap" style="width:10%!important;">Creator SR</th>
                    <th class="center text-nowrap" style="width:10%!important;">Owner SR</th>
                    <th class="center text-nowrap" style="width:10%!important;">SR ID</th>
                    <th class="center text-nowrap" style="width:10%!important;">SR State</th>
                    <th class="center text-nowrap" style="width:10%!important;">SR Status</th>
                    <th class="center text-nowrap" style="width:10%!important;">Action By</th>
                    <th class="center text-nowrap" style="width:10%!important;">Action Date</th>
                    <th class="center text-nowrap" style="width:10%!important;">Pool name</th>
                    <th class="center text-nowrap" style="width:10%!important;">Remark</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="18" class="center">@Resource.Msg_NoRecords</td>
                </tr>
            </tbody>
        </table>
    </div>
}
else
{
    string sortField = Model.SearchFilter.SortField;
    string sortOrder = Model.SearchFilter.SortOrder;

    <div class="form-inline nopadding">
        <div class="form-group">
            @Html.Raw(Html.Pager(
                new Options
                {
                    PageSize = Model.SearchFilter.PageSize,
                    TotalItemCount = Model.SearchFilter.TotalRecords,
                    CurrentPage = Model.SearchFilter.PageNo,
                    ItemTexts = new ItemTexts
                    {
                        First = "<i class='fa fa-step-backward' style='font-size: 0.8em'></i>",
                        Previous = "<i class='fa fa-caret-left'></i>",
                        Next = "<i class='fa fa-caret-right'></i>",
                        Last = "<i class='fa fa-step-forward' style='font-size: 0.8em'></i>"
                    },
                    IsShowFirstLast = true,
                    CssClass = "pager",
                    IsShowInputPage = true
                },
                new { PageSize = ViewBag.PageSize }))

        </div>
        <div class="form-group">
            @Html.DropDownList("PageSize", new SelectList(ViewBag.PageSizeList, "Key", "Value"), new { @class = "form-control input-xs", id = "pagesizelist" })
        </div>
        <div class="form-group text-nowrap margin-left-8">
            <strong>
                @MvcHtmlString.Create(string.Format(Resource.Lbl_Paging, @Model.SearchFilter.FirstPageIndex, @Model.SearchFilter.LastPageIndex, @Model.SearchFilter.TotalRecordsDisplay))
            </strong>
        </div>
    </div>
    <div class="table-responsive">
        <table id="tblJobList" class="table datatable" style="width:1890px!important;">
            <thead>
                <tr>
                    <th class="center text-nowrap">Action</th>
                    <th class="center text-nowrap">@LabelForSort("Attach File", "AttachFile", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Channel", "Channel", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("From", "From", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Job Status", "JobStatus", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Job Date", "JobDate", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Subject", "Subject", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("ชื่อลูกค้า", "FirstName", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("นามสกุลลูกค้า", "LastName", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Creator SR", "CreatorSR", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Owner SR", "OwnerSR", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("SR ID", "SRID", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("State", "State", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Status", "Status", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Action By", "ActionBy", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Action Date", "ActionDate", sortField, sortOrder)</th>
                    <th class="center text-nowrap">@LabelForSort("Pool name", "Poolname", sortField, sortOrder)</th>
                    <th class="center text-nowrap">Remark</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int rowIndex = 1;
                }
                @foreach (var item in Model.CommunicationPoolList)
                {
                    string rowId = "act_" + (rowIndex++);
                    <tr>
                        <td class="center text-nowrap">
                            @if (item.Status == 0)
                            {
                                <a href="javascript:;" class="add" title="New SR" onclick="return confirmNewSR('@item.JobId');"></a>
                                <span class="line-space"></span>
                            }
                            <a href="javascript:;" class="view" title="View" onclick="initCommPoolEdit('@item.JobId');"></a>
                        </td>
                        <td class="center">@item.AttachmentsDisplay</td>
                        <td class="left text-nowrap">@item.ChannelEntity.Name</td>
                        <td class="left text-nowrap">@Html.Raw(StringHelpers.DisplayWithMaxLength(item.SenderName, 50))</td>
                        <td class="center text-nowrap">@item.StatusDisplay</td>
                        <td class="center text-nowrap">@item.CreateDateDisplay</td>
                        <td class="left text-nowrap">
                            @*<div style="width:300px!important">@item.Subject</div>*@
                            @if (item.Subject != null && item.Subject.Length > Constants.DisplayMaxLength)
                            {
                                @StringHelpers.DisplayLimitLength(item.Subject) <span onclick="$jq('#@rowId').toggle('slow')" style="cursor:pointer">...</span>
                            }
                            else
                            {
                                @item.Subject
                            }
                        </td>
                        @if (item.ServiceRequest != null)
                        {
                            if (item.ServiceRequest.Customer != null)
                            {
                                <td class="left text-nowrap">@item.ServiceRequest.Customer.FirstNameThaiEng</td>
                                <td class="left text-nowrap">@item.ServiceRequest.Customer.LastNameThaiEng</td>
                            }
                            else
                            {
                                <td></td>
                                <td></td>
                            }
                            if (item.ServiceRequest.CreateUser != null)
                            {
                                <td class="left text-nowrap">@item.ServiceRequest.CreateUser.FullName</td>
                            }
                            else
                            {
                                <td></td>
                            }
                            if (item.ServiceRequest.Owner != null)
                            {
                                <td class="left text-nowrap">@item.ServiceRequest.Owner.FullName</td>
                            }
                            else
                            {
                                <td></td>
                            }
                            <td class="center text-nowrap">@item.ServiceRequest.SrNo</td>
                            <td class="center text-nowrap">@item.ServiceRequest.SRStateName</td>
                            <td class="center text-nowrap">@item.ServiceRequest.StatusDisplay</td>
                        }
                        else
                        {
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        }

                        @if (item.UpdateUser != null)
                        {
                            <td class="left text-nowrap">@item.UpdateUser.FullName</td>
                        }
                        else
                        {
                            <td></td>
                        }
                        <td class="center text-nowrap">@item.UpdateDateDisplay</td>
                        <td class ="left text-nowrap">@item.PoolEntity.PoolName</td>
                        <td class="left text-nowrap">
                            @if (item.Remark != null && item.Remark.Length > Constants.DisplayMaxLength)
                            {
                                @StringHelpers.DisplayLimitLength(item.Remark) <span onclick="$jq('#@rowId').toggle('slow')" style="cursor:pointer">...</span>
                            }
                            else
                            {
                                @item.Remark
                            }
                        </td>
                    </tr>
                    if (@item.Remark != null || @item.Subject != null)
                    {

                        <tr id="@rowId" style="display:none">
                            <td colspan="18">
                                <table class="activity_detail">
                                    <tr>
                                        <td style="width:100px">Subject :</td>
                                        <td>@item.Subject</td>
                                    </tr>
                                    <tr>
                                        <td style="width:100px">Remark :</td>
                                        <td>@item.Remark</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
}

Application/CSM/CSM.Web/Views/Job/_RemarkCloseJob.cshtml
@model CSM.Web.Models.JobViewModel

<div class="modal-dialog modal-sm" style="min-width:800px;">
    <div id="dvRemarkForm" class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h5 class="modal-title">ระบุ Remark เพื่อ Close Job</h5>
            @Html.HiddenFor(model => model.JobId, new { @id = "hddJobId" })
            @Html.HiddenFor(model => model.JobStatus, new { @id = "hddJobStatus" })
        </div>
        <div class="modal-body form-horizontal">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label col-md-2 left-label">Remark<span class="require">*</span> :</label>
                        <div class="col-md-9 nopadding">
                            @Html.TextAreaFor(model => model.Remark, new
                            {
                                @id = "txtRemark",
                                @class = "form-control input-sm",
                                @style = "min-width:550px;min-height: 150px;"
                            })
                            @Html.ValidationMessageFor(model => model.Remark)

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="modal-footer">
                <div class="col-md-4 text-left">
                </div>
                <div class="col-md-8">
                    <button type="button" class="btn btn-blue btn-sm btn-xsmall" onclick="" id="btnConfirmCloseJob">
                        <i class="fa fa-save"></i>&nbsp;Confirm
                    </button>
                    @*<button type="button" class="btn btn-gray btn-sm btn-xsmall" data-dismiss="modal" aria-hidden="true">Cancel</button>*@
                    <button type="button" class="btn btn-gray btn-sm btn-xsmall" onclick="" id="btnCancelCloseJob">
                        Cancel
                    </button>

                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $jq(function () {

        $jq('#btnConfirmCloseJob').click(function (e) {
            e.preventDefault();
            confirmCloseJob();
            return false;
        });

        $jq("#btnCancelCloseJob").click(function (e) {
            e.preventDefault();
            var msg = 'ต้องการยกเลิกการบันทึกข้อมูลใช่หรือไม่?';
            if ($jq.trim(msg) != '') {
                doModal('dvAlertMsg', 'Message Dialog', msg, 'doCancelCloseJob()', 'Confirm');
            }
            return false;
        });

    });

    function doCancelCloseJob() {
        hideModal('modalWindow');
        $jq('#remarkCloseJobModal').modal('hide');
        return false;
    }

    function confirmCloseJob() {
        clearServerErrors();
        var objJob = $jq("#form2").serialize();

        $jq.ajax({
            url: '@Url.Action("SaveRemarkCloseJob", "Job")',
            type: "POST",
            data: objJob,
            beforeSend: function () { $jq("#dvLoading").show(); },
            complete: function () { $jq("#dvLoading").hide(); },
            success: function (result) {
                if (result.Valid === true) {
                    $jq('#remarkCloseJobModal').modal('hide');
                    initSearch();
                }
                else if (result.Error != '') {
                    $jq('#remarkCloseJobModal').modal('hide');
                    reloadCommPoolEditWithMessage();
                }
                 else {
                    showServerErrors(result);
                }
            },
            error: function (xhr) {
                var handleMsg = '@CSM.Common.Resources.Resource.Error_System';
                ajaxErrorHandling(xhr, handleMsg, '@FormsAuthentication.LoginUrl', '@Url.Action("AccessDenied", "User")');
            }
        });

        return false;
    }

    function reloadCommPoolEditWithMessage() {
        
        var actionUrl = '@Url.Action("ReloadCommPoolEditWithMessage", "Job")';
        $jq('#dvTarget').html('');
        var inputJobId = $jq("<input>").attr("type", "hidden").attr("name", "jobId").val($jq('#hddJobId').val());
        var inputToken = $jq("<input>").attr("type", "hidden").attr("name", "__RequestVerificationToken").val(getAntiForgeryToken());
        $jq('#dvTarget').append('<form action="' + actionUrl + '" method="POST" class="hidden"></form>');
        $jq('#dvTarget form').append($jq(inputJobId));
        $jq('#dvTarget form').append($jq(inputToken));
        $jq('#dvTarget form').submit();
    }
    
</script>