Application/CSM/CSM.Web/Models/QuestionGroupViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using CSM.Common.Resources;
using CSM.Entity;

namespace CSM.Web.Models
{
    public class QuestionGroupViewModel
    {
        public IEnumerable<QuestionGroupItemEntity> QuestionGroupList { get; set; }
        public QuestionGroupSearchFilter SearchFilter { get; set; }
        public List<SelectListItem> QuestionGroupIsActiveList { get; set; }
        public QuestionGroupQuestionSearchFilter QuestionGroupQuestionSearchFilter { get; set; }
        public int? QuestionGroupId { get; set; }
        public string QuestionGroupName { get; set; }
        public bool Status { get; set; }

        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }

        public int CreateUser { get; set; }
        public string CreateUserName { get; set; }
        public int UpdateUser { get; set; }
        public string UpdateUserName { get; set; }
        public List<QuestionGroupTableModel> QuestionGroupTableList { get; set; } 


    }

    public class QuestionGroupTableModel
    {
        public int? id { get; set; }
        public string question_name { get; set; }
    }

    public class QuestionGroupEditViewModel
    {
        public int? QuestionGroupId { get; set; }
        public int? QuestionId { get; set; }
        [Display(Name = "ชื่อกลุ่มคำถาม")]
        [Required(ErrorMessageResourceType = typeof(SRResource), ErrorMessageResourceName = "ValidationRequiredField")]
        public string QuestionGroupName { get; set; }
        public string QuestionGroupProductName { get; set; }
        public bool? Status { get; set; }
        public List<SelectListItem> StatusList { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }
        public int CreateUser { get; set; }
        public string CreateUserName { get; set; }
        public int UpdateUser { get; set; }
        public string UpdateUserName { get; set; }
        public string QuestionGroupProductGroup { get; set; }
        public string DisplayCreateDate { get; set; }
        public string DisplayUpdateDate { get; set; }

        [Display(Name = "Product")]
        [Required(ErrorMessageResourceType = typeof(SRResource), ErrorMessageResourceName = "ValidationRequiredLookup")]
        public int? QuestionGroupProductId { get; set; }

        public string QuestionGroupDescription { get; set; }
        public QuestionSelectSearchFilter SearchFilter { get; set; }
        public IEnumerable<QuestionItemEntity> QuestionList { get; set; }
        public QuestionGroupInQuestionSearchFilter QuestionGroupInQuestionSearchFilter { get; set; }
        public IEnumerable<QuestionGroupQuestionItemEntity> QuestionGroupInQuestionList { get; set; }

        public string QuestionGroupProductIds { get; set; }

    }
    public class QuestionGroupSaveViewModel
    {
        public int? QuestionGroupId { get; set; }
        public int? QuestionId { get; set; }
        public string QuestionGroupName { get; set; }
        public string QuestionGroupProduct { get; set; }
        public string QuestionGroupProductGroup { get; set; }
        public bool Status { get; set; }
        public List<SelectListItem> StatusList { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }

        public int CreateUser { get; set; }
        public string CreateUserName { get; set; }
        public int UpdateUser { get; set; }
        public string UpdateUserName { get; set; }
        public string QuestionGroupProductIds { get; set; }
        public string Description { get; set; }
    }

    public class QuestionGroupProductViewModel
    {
        public string Product { get; set; }
        public string ProductGroup { get; set; }

    } 
}

Application/CSM/CSM.Web/Controllers/QuestionGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using CSM.Business;
using CSM.Common.Utilities;
using CSM.Entity;
using CSM.Web.Controllers.Common;
using CSM.Web.Filters;
using CSM.Web.Models;
using log4net;
using System.Globalization;

namespace CSM.Web.Controllers
{
    [CheckUserSession]
    public class QuestionGroupController : BaseController
    {
        private IProductFacade _productFacade;
        private IQuestionGroupFacade _questionGroupFacade;
        private LogMessageBuilder _logMsg = new LogMessageBuilder();
        private static readonly ILog Logger = LogManager.GetLogger(typeof(ContactController));

        public ActionResult Index()
        {
            var questionGroupVM = new QuestionGroupViewModel();
            questionGroupVM.QuestionGroupIsActiveList = new List<SelectListItem>();
            questionGroupVM.QuestionGroupIsActiveList.Add(new SelectListItem { Text = "ทั้งหมด", Value = "all" });
            questionGroupVM.QuestionGroupIsActiveList.Add(new SelectListItem { Text = "Active", Value = "true" });
            questionGroupVM.QuestionGroupIsActiveList.Add(new SelectListItem { Text = "Inactive", Value = "false" });
            questionGroupVM.Status = true;

            questionGroupVM.SearchFilter = new QuestionGroupSearchFilter
            {
                QuestionGroupName = null,
                ProductId = null,
                Status = "",
                PageNo = 1,
                PageSize = 15,
                SortField = string.Empty,
                SortOrder = "ASC"
            };

            return View(questionGroupVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? questionGroupId)
        {
            if (questionGroupId.HasValue)
            {
                var questionGroupVM = new QuestionGroupEditViewModel();
                _questionGroupFacade = new QuestionGroupFacade();

                //get area section
                QuestionGroupItemEntity questionGroupItemEntity = _questionGroupFacade.GetQuestionGroupById(questionGroupId.Value);
                questionGroupVM.QuestionGroupId = questionGroupItemEntity.QuestionGroupId;
                questionGroupVM.QuestionGroupName = questionGroupItemEntity.QuestionGroupName;
                questionGroupVM.QuestionGroupProductName = questionGroupItemEntity.QuestionGroupProduct;
                questionGroupVM.QuestionGroupProductId = questionGroupItemEntity.QuestionGroupProductId;
                questionGroupVM.CreateUserName = questionGroupItemEntity.CreateUserName != null ? questionGroupItemEntity.CreateUserName.FullName : "";
                questionGroupVM.UpdateUserName = questionGroupItemEntity.UpdateUserName != null ? questionGroupItemEntity.UpdateUserName.FullName : "";
                questionGroupVM.DisplayCreateDate = DateUtil.ToStringAsDateTime(questionGroupItemEntity.CreateDate);
                questionGroupVM.DisplayUpdateDate = DateUtil.ToStringAsDateTime(questionGroupItemEntity.UpdateDate);
                questionGroupVM.QuestionGroupDescription = questionGroupItemEntity.Description;

                questionGroupVM.Status = questionGroupItemEntity.Status;
                questionGroupVM.StatusList = new List<SelectListItem>();
                questionGroupVM.StatusList.Add(new SelectListItem { Text = "Active", Value = "true" });
                questionGroupVM.StatusList.Add(new SelectListItem { Text = "Inactive", Value = "false" });

                questionGroupVM.QuestionGroupInQuestionSearchFilter = new QuestionGroupInQuestionSearchFilter
                {
                    QuestionGroupId = null,
                    PageNo = 1,
                    PageSize = 15,
                    SortField = "GroupName",
                    SortOrder = "ASC"
                };

                questionGroupVM.SearchFilter = new QuestionSelectSearchFilter
                {
                    QuestionName = string.Empty,
                    QuestionIdList = string.Empty,
                    PageNo = 1,
                    PageSize = 15,
                    SortField = "QuestionName",
                    SortOrder = "ASC"
                };

                // Get sub area section
                return View(questionGroupVM);
            }

            return View("Create");
        }

        public ActionResult Create()
        {
            var model = new QuestionGroupEditViewModel();
            model.SearchFilter = new QuestionSelectSearchFilter
            {
                QuestionName = string.Empty,
                QuestionIdList = string.Empty,
                PageNo = 1,
                PageSize = 15,
                SortField = "QuestionName",
                SortOrder = "ASC"
            };

            ViewBag.PageSize = model.SearchFilter.PageSize;
            ViewBag.Message = string.Empty;

            ViewBag.CreateUsername = UserInfo.FullName;
            ViewBag.UpdateUsername = UserInfo.FullName;
            ViewBag.CreateDate = DateTime.Now;
            ViewBag.UpdateDate = DateTime.Now;

            return View(model);
        }

        [HttpPost]
        public ActionResult GetProductList()
        {
            _productFacade = new ProductFacade();
            return Json(new
            {
                IsSuccess = true,
                Products = _productFacade.GetProductList().Select(p => new
                {
                    p.ProductId,
                    p.ProductName
                }).ToList(),
            });
        }

        [HttpPost]
        public JsonResult Autocomplete(string Prefix)
        {
            _questionGroupFacade = new QuestionGroupFacade();
            var totalCount = 0;
            List<QuestionGroupProductEntity> list = _questionGroupFacade.GetProductList(Prefix, ref totalCount);
            return Json(list.Select(item => new
            {
                Product = item.Product,
                ProductGroup = item.ProductGroup
            }));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchQuestionGroupQuestion(QuestionGroupInQuestionSearchFilter searchFilter)
        {
            Logger.Info(_logMsg.Clear().SetPrefixMsg("Search QuestionInQuestionGroup").ToInputLogString());

            try
            {
                if (ModelState.IsValid)
                {
                    _questionGroupFacade = new QuestionGroupFacade();
                    var model = new QuestionGroupEditViewModel();
                    model.QuestionGroupInQuestionSearchFilter = searchFilter;
                    model.QuestionGroupInQuestionList = _questionGroupFacade.GetQuestionListById(model.QuestionGroupInQuestionSearchFilter);

                    return PartialView("~/Views/QuestionGroup/_QuestionInQuestionGroupList.cshtml", model);
                }

                return Json(new
                {
                    Valid = false,
                    Error = string.Empty
                });
            }
            catch (Exception ex)
            {
                Logger.Error("Exception occur:\n", ex);
                Logger.Info(_logMsg.Clear().SetPrefixMsg("Search SubArea").Add("Error Message", ex).ToFailLogString());
                return Error(new HandleErrorInfo(ex, this.ControllerContext.RouteData.Values["controller"].ToString(),
                    this.ControllerContext.RouteData.Values["action"].ToString()));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchQuestion(BootstrapParameters parameters, string questionName, string questionIdList)
        {
            if (ModelState.IsValid)
            {
                var totalCount = 0;
                _questionGroupFacade = new QuestionGroupFacade();
                List<QuestionItemEntity> list = _questionGroupFacade.SearchQuestionGroupQuestion(parameters.offset, parameters.limit, questionName, questionIdList, ref totalCount);

                return Json(new BootstrapTableResult
                {
                    total = totalCount,
                    rows = list.Select(item => new
                    {
                        id = item.QuestionId,
                        // action = string.Format("<a onClick='editQuestion({0})' class='btnEdit'><i class='fa fa-edit'></i></a>", item.QuestionId),
                        question_name = item.QuestionName,
                        status = item.Status.HasValue ? item.Status.Value ? "Active" : "Inactive" : "Inactive",
                        update_name = string.IsNullOrEmpty(item.UpdateUserName.FullName) ? item.CreateUserName.FullName : item.UpdateUserName.FullName,
                        update_date = !item.UpdateDate.HasValue ? DateUtil.ToStringAsDateTime(item.CreateDate) : DateUtil.ToStringAsDateTime(item.UpdateDate)
                    }).ToList()
                });
            }

            return Json(new
            {
                Valid = false,
                Error = string.Empty
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveQuestionGroup(QuestionGroupSaveViewModel questionGroupSaveVM, string idQuestions)
        {
            Logger.Info(_logMsg.Clear().SetPrefixMsg("Save Group Question").ToInputLogString());
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(questionGroupSaveVM.QuestionGroupProductIds))
                    {
                        ModelState.AddModelError("QuestionGroupProductIds", "กรุณาระบุ Product อย่างน้อย 1 รายการ");

                        return Json(new
                        {
                            Valid = false,
                            Error = string.Empty,
                            Errors = GetModelValidationErrors()
                        });
                    }

Application/CSM/CSM.Web/Views/QuestionGroup/Index.cshtml
@using CSM.Common.Resources
@model CSM.Web.Models.QuestionGroupViewModel
@{
    ViewBag.Title = "Search Group Question";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section MainMenu
{
    @Html.Action("MainMenu", "MenuNavigator", new { selectedMenu = CSM.Entity.MenuCode.Master })
}
@section Breadcrumb {
    @*<strong class="font-blue">Group Question &rsaquo;&rsaquo;</strong>*@
    <strong class="font-blue"> @Html.ActionLink(Resource.Lbl_Master, "Index", "Configuration", null, new { @class = "font-blue" }) </strong>
    <strong class="font-green-jungle">&rsaquo;&rsaquo; Search Group Question</strong>
}
<div class="form-horizontal">
    <h5 class="form-title">Search Group Question</h5>
    <hr class="dotted-line" />
    <div class="row margin-top-15">
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label class="control-label">กลุ่มคำถาม :</label>
                </div>
                <div class="col-sm-4">
                    <input type="text" class="form-control input-sm" id="txtSearchQuestionGroupName" />
                </div>
                <div class="col-sm-2">
                    <label class="control-label">สถานะ :</label>
                </div>
                <div class="col-sm-4">
                    @Html.DropDownListFor(model => model.Status, Model.QuestionGroupIsActiveList, Resource.Ddl_PleaseSelect,new {@class = "form-control input-sm", id = "selectStatus"})
                </div>
            </div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-sm-2">
                    <label class="control-label">Product :</label>
                </div>
                <div class="col-sm-4">
                    <input type="text" class="form-control input-sm" id="txtSearchQuestionGroupProduct" />
                </div>
            </div>
        </div>
    </div>
    <hr class="dashed-line" />
    <div class="row">
        <form action="@Url.Action("Create", "QuestionGroup")" method="POST">
            <button class="btn btn-sm btn-success"><i class="fa fa-plus"></i> New Group Question</button>
            <div class="pull-right">
                <span id="btnSearch" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Search</span>
                <span id="btnClearForm" class="btn btn-sm btn-default"><i class="fa fa-file-o"></i> Clear</span>
            </div>
        </form>
    </div>
    <div class="clearfix"></div>
    <hr class="dashed-line" />
    <div class="clear"></div>

    <div id="dvSearchQuestionGroup">
        @if (Model.QuestionGroupList != null)
        {
            Html.RenderPartial("~/Views/QuestionGroup/_QuestionGroupList.cshtml", Model);
        }
    </div>

</div>
<div id="dvTarget"></div>
@Html.Partial("_Antiforgery")

@section masterjs
{
    <style type="text/css">
        .input-page {
            width: 30px;
        }

        .btnEdit {
            cursor: pointer;
        }
    </style>
    <script type="text/javascript">
        var searchFilter;
        var successFilter;

        $jq(document).ready(function () {

            initializeSearchFilter();
            initializePaging();
            initialAutoComplete();

            $jq('#btnSearch').click(onBtnSearchClick);
            $jq("#btnClearForm").click(onBtnClearClick);

            $jq("#selectStatus").val("");
        });

        function initialAutoComplete() {
            initialAutoCompleteProduct();
        }

        function initialAutoCompleteProduct() {
            $jq("#txtSearchQuestionGroupProduct").select2({
                placeholder: '@Resource.Ddl_AutoComplete',
                minimumInputLength: '@CSM.Common.Utilities.Constants.MinLenght.AutoComplete',
                language: "th",
                allowClear: true,
                ajax: {
                    url: "@Url.Action("AutoCompleteSearchProductForQuestionGroup", "AutoComplete")",
                    dataType: 'json',
                    type: "post",
                    quietMillis: 150,
                    data: function(keyword) {
                        return {
                            keyword: keyword
                        };
                    },
                    results: function (data) {
                        if (data.RedirectUrl != undefined) {
                            topLocation(data.RedirectUrl);
                            return;
                        }
                        return {
                            results: $jq.map(data, function(item) {
                                return {
                                    text: item.ProductName,
                                    id: item.ProductId
                                }
                            })
                        };
                    },
                    error: function (xhr) {
                        var handleMsg = '@CSM.Common.Resources.Resource.Error_System';
                        ajaxErrorHandling(xhr, handleMsg, '@FormsAuthentication.LoginUrl', '@Url.Action("AccessDenied", "User")');
                    }
                }
            });
        }

        function editQuestionGroup(questionGroupId) {
            $jq('#hdnFrm').html('<form action="@Url.Action("Edit","QuestionGroup")" name="frmEdit" id="frmEdit" method="post" style="display:none;">@Html.AntiForgeryToken()<input type="text" name="QuestionGroupId" value="' + questionGroupId + '" /></form>');
            document.forms['frmEdit'].submit();
        }


        function onBtnSearchClick() {
            clearServerErrors();
            searchFilter.QuestionGroupName = $jq("#txtSearchQuestionGroupName").val(),
            searchFilter.ProductId = $jq("#txtSearchQuestionGroupProduct").val(),
            searchFilter.Status = $jq("#selectStatus").val(),
            searchFilter.PageNo = 1;

            if (searchFilter.QuestionGroupName == "" &&
                searchFilter.ProductId == "" &&
                searchFilter.Status == "") {
                var warningMsg = '@Resource.Msg_EnteredAtLeastOneCriteria';
                doModal('dvAlertMsg', 'Message Dialog', warningMsg, '', '');
                return false;
            }

            loadQuestionGroupList();
        }

        function onBtnClearClick() {
            $jq("#selectStatus").val("");
            $jq("#txtSearchQuestionGroupName").val("");
            $jq("#txtSearchQuestionGroupProduct").select2("val", "");

            $jq("#dvSearchQuestionGroup").html('');
        }

        function loadQuestionGroupList() {

            $jq.ajax({
                    url: "@Url.Action("SearchQuestionGroupList", "QuestionGroup")",
                    method: "POST",
                    data: searchFilter,
                    beforeSend: function() { $jq("#dvLoading").show(); },
                    complete: function() { $jq("#dvLoading").hide() }
                })
                .done(function (result) {
                    if (isLoginForm(result)) {
                        location.replace('@FormsAuthentication.LoginUrl');
                        return;
                    }
                    if (result.Valid == null) {
                        $jq("#dvSearchQuestionGroup").html('');
                        successFilter = searchFilter;
                        $jq("#dvSearchQuestionGroup").html(result);
                        initializePaging();
                    } else {
                        showServerErrors(result);
                    }
                })
                .fail(function() {
                    if (xhr.status === 401) {
                        location.replace('@FormsAuthentication.LoginUrl');
                        return;
                    } else {
                        var errorMsg = String.format('<strong>Error:</strong>&nbsp;{0}', '@CSM.Common.Resources.Resource.Error_System');
                        doModal('dvAlertMsg', 'Message Dialog', errorMsg, '', '');
                    }
                });
        }

        function initializeSearchFilter() {
            searchFilter = {
                QuestionGroupName: $jq("#txtSearchQuestionGroupName").val(),
                ProductId: $jq("#txtSearchQuestionGroupProduct").val(),
                Status: $jq("#selectStatus").val(),
                PageNo: '@Model.SearchFilter.PageNo',
                PageSize: '@Model.SearchFilter.PageSize',
                SortField: '@Model.SearchFilter.SortField',
                SortOrder: '@Model.SearchFilter.SortOrder',
                __RequestVerificationToken: getAntiForgeryToken()
            }

            successFilter = searchFilter;
        }

        function initializePaging() {
            $jq("#dvSearchQuestionGroup .input-page").change(function (event) {
                searchFilter = successFilter;
                searchFilter.PageNo = $jq(this).val();
                loadQuestionGroupList();
                return false;
            }).keypress(function (event) {
                return validateDigit(event);
            });

            $jq("#dvSearchQuestionGroup #pagesizelist").change(function (event) {
                searchFilter = successFilter;
                searchFilter.PageNo = "1";
                searchFilter.PageSize = $jq(this).val();
                loadQuestionGroupList();
                return false;
            });

            $jq('#dvSearchQuestionGroup .pagination ul li a').on('click', function (event) {
                searchFilter = successFilter;
                searchFilter.PageNo = getUrlParameter($jq(this).attr("href"), "page");
                loadQuestionGroupList();
                return false;
            });
        }

        function sortField(selectedSortField) {
            if (selectedSortField == searchFilter.SortField)
                searchFilter.SortOrder = (searchFilter.SortOrder == 'ASC') ? 'DESC' : 'ASC';
            else
                searchFilter.SortOrder = 'ASC';
            searchFilter.SortField = selectedSortField;
            searchFilter.PageNo = 1;
            loadQuestionGroupList();
        }

        function onEditClick(questionGroupId) {
            $jq('#dvTarget').html('<form action="@Url.Action("Edit","QuestionGroup")" name="frmEdit" id="frmEdit" method="post" style="display:none;">@Html.AntiForgeryToken()<input type="text" name="questionGroupId" value="' + questionGroupId + '" /></form>');
            document.forms['frmEdit'].submit();
        }

    </script>
}

Application/CSM/CSM.Web/Views/QuestionGroup/_QuestionGroupList.cshtml
@using CSM.Common.Resources
@using CSM.Common.Utilities
@using MvcPaging
@model CSM.Web.Models.QuestionGroupViewModel
@helper LabelForSort(string headerText, string fieldName, string sortField, string sortOrder)
{
    <a href="javascript:;" onclick="sortField('@fieldName');return false;">
        @headerText
        @if (fieldName.ToLower().Equals(sortField.ToLower()))
        {
            if (sortOrder.Equals("ASC"))
            {<i class="fa fa-sort-asc"></i>}
            else
            {<i class="fa fa-sort-desc"></i> }
        }
        else
        {<i class="fa fa-sort"></i>}
    </a>
}
@if (Model.QuestionGroupList == null || Model.SearchFilter.TotalRecords == 0)
{
    <div class="table-responsive margin-top-10">
        <table class="table table-hover datatable">
            <thead>
                <tr>
                    <th style="width: 80px !important;" class="center">Action</th>
                    <th>กลุ่มคำถาม</th>
                    <th>จำนวนคำถาม</th>
                    <th>Product</th>
                    <th style="width: 200px !important;">สถานะ</th>
                    <th>แก้ไขโดย</th>
                    <th style="width: 200px !important;">วันที่แก้ไข</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="14" class="center">@Resource.Msg_NoRecords</td>
                </tr>
            </tbody>
        </table>
    </div>
}
else
{
    string sortField = Model.SearchFilter.SortField;
    string sortOrder = Model.SearchFilter.SortOrder;

    <div class="form-inline nopadding">
        <div class="form-group">
            @Html.Raw(Html.Pager(
                new Options
                {
                    PageSize = Model.SearchFilter.PageSize,
                    TotalItemCount = Model.SearchFilter.TotalRecords,
                    CurrentPage = Model.SearchFilter.PageNo,
                    ItemTexts = new ItemTexts
                    {
                        First = "<i class='fa fa-step-backward' style='font-size: 0.8em'></i>",
                        Previous = "<i class='fa fa-caret-left'></i>",
                        Next = "<i class='fa fa-caret-right'></i>",
                        Last = "<i class='fa fa-step-forward' style='font-size: 0.8em'></i>"
                    },
                    IsShowFirstLast = true,
                    CssClass = "pager",
                    IsShowInputPage = true
                },
                new {PageSize = ViewBag.PageSize}))
        </div>
        <div class="form-group">
            @Html.DropDownList("PageSize", new SelectList(new Dictionary<string, int> {{"15", 15}, {"30", 30}}, "Key", "Value"), new {@class = "form-control input-xs", id = "pagesizelist"})
        </div>
        <div class="form-group text-nowrap margin-left-8">
            <strong>
                @MvcHtmlString.Create(string.Format(Resource.Lbl_Paging, @Model.SearchFilter.FirstPageIndex, @Model.SearchFilter.LastPageIndex, @Model.SearchFilter.TotalRecords))
            </strong>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="table-responsive margin-top-10">
        <table class="table table-hover datatable">
            <thead>
                <tr>
                    <th class="center" style="width: 80px !important;">Action</th>
                    <th>กลุ่มคำถาม</th>
                    <th>จำนวนคำถาม</th>
                    <th>Product</th>
                    <th style="width: 200px !important;">สถานะ</th>
                    <th>แก้ไขโดย</th>
                    <th style="width: 200px !important;">วันที่แก้ไข</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.QuestionGroupList)
                {
                    <tr>
                        <td class="center">
                            <a href='javascript:;' class="edit-active" onclick='onEditClick(@item.QuestionGroupId)'></a>
                        </td>
                        <td>@item.QuestionGroupName</td>
                        <td class="center">
                            @item.QuestionNo
                        </td>
                        <td>
                            @item.ProductName
                        </td>
                        <td class="center">
                            @{
                                if (item.Status.HasValue)
                                {
                                    @Html.Raw(item.Status.Value ? "Active" : "Inactive")
                                }
                            }
                        </td>
                        <td>
                            @{
                                if (item.UpdateUserName != null)
                                {
                                    @item.UpdateUserName.FullName
                                }
                            }
                        </td>
                        <td>
                            @DateUtil.ToStringAsDateTime(item.UpdateDate)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}